name: Exportar CSV automaticamente

on:
  schedule:
    - cron: '0 * * * *'  # A cada hora (UTC)
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  exportar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar exportador
        run: python export.py

      - name: Commit e push do CSV atualizado
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add dados/combates_2024.csv
          git commit -m "Atualiza CSV automaticamente [skip ci]" || echo "Nada para commit"
          git push
