name: Atualizar CSV

on:
  schedule:
    - cron: '*/3 * * * *'  # A cada 3 minutos
  workflow_dispatch:

jobs:
  exportar:
    runs-on: ubuntu-latest
    env:
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_DATABASE: ${{ secrets.PG_DATABASE }}

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar exportador
        run: python export.py

      - name: Commit e push do CSV atualizado
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dados/combates_2024.csv
          git commit -m "Atualiza CSV automaticamente" || echo "Nenhuma alteração"
          git push
